print()
salario = float(input("Digite o salario atual:"))
reajuste = float(input("Digite o percentual do reajuste:"))
print()
print('O Salario atual é: R${:.2f}'.format(salario))
print('Percentual de reajuste: {:.2f}%'.format(reajuste))
print('Valor do reajuste: R${:.2f}'.format(salario*(reajuste/100)))
print('Valor do novo salário: R${:.2f}'.format(salario+(salario*(reajuste/100))))
print()